modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="ARR"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="${modId}" #mandatory
version="${version}" #mandatory ugh
displayName="${modName}" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="${discord}" #optional
#logoFile="croptopia-forge.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Thonk" #optional
description='''
${description}
'''
[[dependencies.${modId}]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[37,)" #mandatory
   ordering="NONE"
   side="SERVER"
# Here's another dependency
[[dependencies.${modId}]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,)"
   ordering="NONE"
   side="SERVER"
[[dependencies.${modId}]]
   modId="epherolib"
   mandatory=true
   versionRange="[0.1.2,)"
   ordering="NONE"
   side="BOTH"
